[project]
name = "vgon"
version = "0.1.0"
description = "Variational Generative Optimization Network (VGON)."
authors = []
requires-python = ">=3.10"

dependencies = [
    "appdirs==1.4.4",
    "asttokens==3.0.0",
    "astunparse==1.6.3",
    "autograd==1.7.0",
    "autoray==0.7.1",
    "cachetools==5.5.2",
    "certifi==2025.4.26",
    "charset-normalizer==3.4.2",
    "clarabel==0.10.0",
    "colorama==0.4.6",
    "comm==0.2.2",
    "contourpy==1.3.2",
    "cvxopt==1.3.2",
    "cvxpy==1.6.0",
    "cvxpylayers==0.1.9",
    "cycler==0.12.1",
    "debugpy==1.8.11",
    "decorator==5.1.1",
    "diastatic-malt==2.15.2",
    "diffcp==1.1.4",
    "exceptiongroup==1.2.2",
    "executing==2.1.0",
    "filelock==3.18.0",
    "fonttools==4.57.0",
    "fsspec==2025.3.2",
    "gast==0.6.0",
    "idna==3.10",
    "ipykernel==6.29.5",
    "ipython==8.31.0",
    "jedi==0.19.2",
    "Jinja2==3.1.6",
    "joblib==1.5.0",
    "jupyter_client==8.6.3",
    "jupyter_core==5.7.2",
    "kiwisolver==1.4.8",
    "MarkupSafe==3.0.2",
    "matplotlib==3.7.2",
    "matplotlib-inline==0.1.7",
    "more-itertools==10.5.0",
    "mpmath==1.3.0",
    "nest-asyncio==1.6.0",
    "networkx==3.4.2",
    "numpy",
    "osqp==1.0.3",
    "packaging==25.0",
    "pandas==1.5.3",
    "parso==0.8.4",
    "PennyLane==0.41.1",
    "PennyLane_Lightning==0.41.0",
    "PICOS==2.5.1",
    "pillow==11.2.1",
    "prompt_toolkit==3.0.48",
    "ptitprince==0.2.7",
    "pure_eval==0.2.3",
    "Pygments==2.18.0",
    "pyparsing==3.0.9",
    "python-dateutil==2.9.0.post0",
    "pytz==2025.2",
    "pyzmq==26.2.0",
    "requests==2.32.3",
    "rustworkx==0.16.0",
    "scipy==1.14.1",
    "scipy-openblas32==0.3.29.0.0",
    "scs==3.2.7",
    "seaborn==0.11.0",
    "six==1.17.0",
    "stack-data==0.6.3",
    "sympy==1.14.0",
    "termcolor==3.1.0",
    "threadpoolctl==3.6.0",
    "tomlkit==0.13.2",
    "toqito>=1.1.2",
    "torch",
    "tornado==6.4.2",
    "traitlets==5.14.3",
    "typing_extensions==4.13.2",
    "tzdata==2025.2",
    "urllib3==2.4.0",
    "wcwidth==0.2.13",
]

[tool.uv.sources]
torch = { index = "pytorch" }

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cpu"
explicit = true