[project]
name = "vgon"
version = "0.1.0"
description = "Variational Generative Optimization Network (VGON)."
authors = []
requires-python = ">=3.10"

dependencies = [
    "torch",
    "pennylane",
]

[project.optional-dependencies]
# 可以保留 plot 组用于明确安装
# uv sync -U --extra plot
# you could cancle 'plot' block to use NumPy2.x.y
plot = [
    "numpy<2",  # for ptiprince requirements only
    "pandas<2", # for ptiprince requirements only
    "seaborn",
    "matplotlib<3.9", # for ptiprince requirements only
    "ptitprince",
    "scipy",
]

[tool.uv.sources]
torch = { index = "pytorch" }
# pennylane = { git = "https://github.com/PennyLaneAI/pennylane.git" }
# seaborn = {git = "https://github.com/mwaskom/seaborn.git"}

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cpu"
explicit = true